server:
  port: 9000  # 授权服务器端口，避免和其他服务冲突

spring:
  application:
    name: authorization-server  # 应用名称
  security:
    oauth2:
      authorization:
        server:
          # 客户端配置（内存方式，最简测试）
          client:
            registration:
              test-client:  # 客户端 ID
                client-id: test-client
                client-secret: '{noop}test-secret'  # 明文密码（生产用加密，这里为了测试）
                authorization-grant-types: authorization_code,refresh_token  # 支持的授权类型
                redirect-uris: http://localhost:8080/login/oauth2/code/test-client  # 回调地址（假设资源服务器跑在 8080）
                scopes: user_info  # 权限范围
  datasource:
    driver-class-name: com.kingbase8.Driver
    username: SYSTEM
    password: 654321
    # 开发环境url
    url: jdbc:kingbase8://frp-dog.com:30893/test?useUnicode=true&characterEncoding=UTF-8
# 生产环境url
#    url: jdbc:kingbase8://192.168.3.21:54321/test?useUnicode=true&characterEncoding=UTF-8
