server:
  port: 9000  # 授权服务器端口，避免和其他服务冲突

spring:
  application:
    name: authorization-server  # 应用名称

  datasource:
    driver-class-name: com.kingbase8.Driver
    username: SYSTEM
    password: 654321
    # 开发环境url
    url: jdbc:kingbase8://frp-dog.com:30893/test?useUnicode=true&characterEncoding=UTF-8
# 生产环境url
#    url: jdbc:kingbase8://192.168.3.21:54321/test?useUnicode=true&characterEncoding=UTF-8
