server:
  port: 9000  # 授权服务器端口，避免和其他服务冲突
  # 【新增】告诉 Spring Boot 采纳来自 Nginx 代理的转发头
  forward-headers-strategy: NATIVE
#  ssl:
#    enabled: true
#    key-store-type: JKS
#    key-store-password: 123456 # 与 GasWellPrediction 中的密码保持一致
#    key-store: classpath:boothttps.jks # 指向你刚刚复制过来的证书文件

spring:
  application:
    name: authorization-server  # 应用名称

  datasource:
    driver-class-name: com.kingbase8.Driver
    username: SYSTEM
    password: 654321
    # 开发环境url
    url: jdbc:kingbase8://frp-dog.com:30893/test?useUnicode=true&characterEncoding=UTF-8
# 生产环境url
#    url: jdbc:kingbase8://192.168.3.21:54321/test?useUnicode=true&characterEncoding=UTF-8
